# Generated by Django 3.1.2 on 2020-10-29 14:12

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={},
        ),
        migrations.AlterModelTable(
            name='authors',
            table='Authors',
        ),
    ]


