# Generated by Django 3.1.2 on 2020-11-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_articleimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimages',
            name='images',
            field=models.ImageField(upload_to='upload7/'),
        ),
    ]
