# Generated by Django 3.1.2 on 2020-11-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_auto_20201111_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='articleimages',
            name='images',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
