# Generated by Django 3.1.2 on 2020-10-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
