# Generated by Django 3.1.2 on 2020-10-30 18:44

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_auto_20201030_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newspaper.myuser')),
            ],
            options={
                'db_table': 'OurUser',
            },
            bases=('newspaper.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
