# Generated by Django 3.1.2 on 2020-11-12 14:54

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_auto_20201112_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
