# Generated by Django 3.1.2 on 2020-11-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0005_auto_20201112_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
