# Generated by Django 3.1.2 on 2020-11-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0007_auto_20201118_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimages',
            name='image_preview',
        ),
        migrations.AlterField(
            model_name='articleimages',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
