# Generated by Django 3.1.3 on 2020-12-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0012_auto_20201122_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
