# Generated by Django 3.1.3 on 2020-12-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0013_auto_20201201_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('mark_published', 'set article as published'),), 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='articleimages',
            options={'verbose_name': 'articles image', 'verbose_name_plural': 'articles images'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='ouruser',
            options={'verbose_name': 'our user', 'verbose_name_plural': 'our users'},
        ),
        migrations.AddField(
            model_name='article',
            name='description_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='first name'),
        ),
    ]
