# Generated by Django 3.1.3 on 2020-12-02 14:01

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0014_auto_20201202_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description_ar',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description_en',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('sport', 'sport'), ('history', 'history'), ('tourism', 'tourism')], max_length=10),
        ),
        migrations.CreateModel(
            name='TestTranslateTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='newspaper.testtranslate')),
            ],
            options={
                'verbose_name': 'test translate Translation',
                'db_table': 'newspaper_testtranslate_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
