# Generated by Django 3.1.3 on 2020-12-02 14:08

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0015_auto_20201202_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtranslatetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='newspaper.testtranslate'),
        ),
        migrations.AlterField(
            model_name='testtranslatetranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
