# Generated by Django 3.1.3 on 2020-12-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0016_auto_20201202_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='testtranslatetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testtranslatetranslation',
            name='master',
        ),
        migrations.AddField(
            model_name='author',
            name='position_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='position_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='TestTranslate',
        ),
        migrations.DeleteModel(
            name='TestTranslateTranslation',
        ),
    ]
