# Generated by Django 3.1.3 on 2020-12-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0019_auto_20201203_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_ar',
            field=models.TextField(default='', null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_en',
            field=models.TextField(default='', null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='article',
            name='category_ar',
            field=models.CharField(choices=[('sport', 'sport'), ('history', 'history'), ('tourism', 'tourism')], max_length=10, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='article',
            name='category_en',
            field=models.CharField(choices=[('sport', 'sport'), ('history', 'history'), ('tourism', 'tourism')], max_length=10, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_en',
            field=models.CharField(max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
