# Generated by Django 3.1.3 on 2020-12-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0020_auto_20201203_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_ar',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_en',
        ),
        migrations.AddField(
            model_name='article',
            name='author_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newspaper.author', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newspaper.author', verbose_name='author'),
        ),
    ]
