# Generated by Django 3.1.3 on 2020-12-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0021_auto_20201203_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text_ar',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
