# Generated by Django 3.1.3 on 2020-12-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0022_auto_20201203_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author_en',
        ),
    ]
