# Generated by Django 3.1.3 on 2020-12-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0023_auto_20201203_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category_en',
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
