# Generated by Django 3.1.2 on 2020-11-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='img',
            new_name='feed_image',
        ),
    ]
