# Generated by Django 3.1.2 on 2020-11-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('blog', '0003_auto_20201125_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_links', to='wagtailimages.image'),
        ),
    ]
