# Generated by Django 3.1.2 on 2020-11-25 13:56

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpagerelatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagerelatedlink',
            name='blog_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='blog.blogpage'),
        ),
    ]
