# Generated by Django 3.1.2 on 2020-11-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201125_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'blogindexpage', 'verbose_name_plural': 'blogindexpages'},
        ),
    ]
