# Generated by Django 3.1.3 on 2020-11-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.advert'),
        ),
    ]
