# Generated by Django 3.1.3 on 2020-12-05 18:18

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpageadvertplacement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpageadvertplacement',
            options={'ordering': ['sort_order'], 'verbose_name': 'advert placement', 'verbose_name_plural': 'advert placements'},
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='advert',
        ),
        migrations.AddField(
            model_name='blogpageadvertplacement',
            name='page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advert_placements', to='blog.blogpage'),
            preserve_default=False,
        ),
    ]
