# Generated by Django 3.1.3 on 2020-12-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201205_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'blog index page', 'verbose_name_plural': 'blog index pages'},
        ),
    ]
