# Generated by Django 3.1.3 on 2020-12-06 13:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201206_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='related_blog',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('images', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
    ]
