# Generated by Django 3.1.3 on 2020-12-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201206_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='related_blog',
            new_name='body',
        ),
    ]
