# Generated by Django 3.1.3 on 2020-12-06 14:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201206_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='footer',
            field=wagtail.core.fields.StreamField([('blog_number', wagtail.core.blocks.RegexBlock(error_messages={'invalid': 'the number of blog is not valid.'}, regex='[0-9]{3}[a-d]')), ('date', wagtail.core.blocks.DateTimeBlock())], null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', group='Hi', help_text='the title of related blog')), ('paragraph', wagtail.core.blocks.RichTextBlock(group='Hi')), ('images', wagtail.images.blocks.ImageChooserBlock()), ('domain', wagtail.core.blocks.FloatBlock())], null=True),
        ),
    ]
