# Generated by Django 3.1.3 on 2020-12-06 14:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201206_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='footer',
            field=wagtail.core.fields.StreamField([('date', wagtail.core.blocks.DateTimeBlock()), ('blog_number', wagtail.core.blocks.RegexBlock(error_messages={'invalid': 'the number of blog is not valid.'}, regex='[0-9]{3}[a-d]')), ('category', wagtail.core.blocks.ChoiceBlock(choices=[('happy', 'Happy'), ('sad', 'Sad')], icon='list')), ('parent_page', wagtail.core.blocks.PageChooserBlock())], null=True),
        ),
    ]
