# Generated by Django 3.1.3 on 2020-12-07 06:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201206_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='footer',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='additional_information',
            field=wagtail.core.fields.StreamField([('date', wagtail.core.blocks.DateTimeBlock()), ('blog_number', wagtail.core.blocks.RegexBlock(error_messages={'invalid': 'the number of blog is not valid.'}, regex='[0-9]{3}[a-d]')), ('category', wagtail.core.blocks.ChoiceBlock(choices=[('history', 'History'), ('sport', 'Sport')], icon='list')), ('author', wagtail.core.blocks.StructBlock([('first_name', wagtail.core.blocks.CharBlock()), ('surname', wagtail.core.blocks.CharBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('biography', wagtail.core.blocks.RichTextBlock())]))], null=True),
        ),
    ]
